#!/bin/bash
# Shell aliases

# Navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ~='cd ~'
alias -- -='cd -'

# List files
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lt='ls -ltr'
alias lh='ls -lh'
alias lS='ls -lSr'

# Grep with color
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Safety nets
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias ln='ln -i'

# Directory operations
alias mkdir='mkdir -pv'
alias rmdir='rmdir -v'

# System info
alias df='df -h'
alias du='du -h'
alias free='free -h'
alias top='htop'
alias ps='ps auxf'
alias psg='ps aux | grep -v grep | grep -i -e VSZ -e'

# Network
alias ports='netstat -tulanp'
alias ping='ping -c 5'
alias fastping='ping -c 100 -i 0.2'

# Git shortcuts
alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gpl='git pull'
alias gd='git diff'
alias gds='git diff --staged'
alias gl='git log --oneline --graph --decorate'
alias gla='git log --oneline --graph --decorate --all'
alias gb='git branch'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gm='git merge'
alias gr='git remote'
alias grs='git remote -v'
alias gst='git stash'
alias gstp='git stash pop'

# Docker (if installed)
alias d='docker'
alias dc='docker-compose'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias di='docker images'
alias dex='docker exec -it'

# Python
alias py='python3'
alias pip='pip3'
alias venv='python3 -m venv'
alias activate='source venv/bin/activate'

# JSON pretty print
alias json='python3 -m json.tool'
alias jsonc='python3 -m json.tool --compact'

# Quick edits
alias bashrc='${EDITOR:-vim} ~/.bashrc'
alias aliases='${EDITOR:-vim} ~/.bash_aliases'
alias vimrc='${EDITOR:-vim} ~/.vimrc'

# System
alias update='sudo apt update && sudo apt upgrade'
alias install='sudo apt install'
alias search='apt search'
alias reboot='sudo reboot'
alias shutdown='sudo shutdown -h now'

# Clipboard (if xclip is installed)
alias clip='xclip -selection clipboard'
alias paste='xclip -selection clipboard -o'

# Date and time
alias now='date +"%Y-%m-%d %T"'
alias today='date +"%Y-%m-%d"'
alias week='date +%V'

# Misc
alias h='history'
alias j='jobs -l'
alias which='type -a'
alias path='echo -e ${PATH//:/\\n}'
alias reload='source ~/.bashrc'
alias cls='clear'
alias myip='curl -s https://ipinfo.io/ip'
alias weather='curl wttr.in'

# Raspberry Pi specific
if [[ -f /proc/cpuinfo ]] && grep -q "Raspberry Pi" /proc/cpuinfo; then
    alias temp='vcgencmd measure_temp'
    alias gpio='gpio readall'
fi

# Functions
# Create and enter directory
mkcd() {
    mkdir -p "$1" && cd "$1"
}

# Extract archives
extract() {
    if [ -f "$1" ]; then
        case "$1" in
            *.tar.bz2) tar xjf "$1" ;;
            *.tar.gz) tar xzf "$1" ;;
            *.bz2) bunzip2 "$1" ;;
            *.rar) unrar e "$1" ;;
            *.gz) gunzip "$1" ;;
            *.tar) tar xf "$1" ;;
            *.tbz2) tar xjf "$1" ;;
            *.tgz) tar xzf "$1" ;;
            *.zip) unzip "$1" ;;
            *.Z) uncompress "$1" ;;
            *.7z) 7z x "$1" ;;
            *) echo "'$1' cannot be extracted" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

# Find in files
fif() {
    grep -r "$1" . 2>/dev/null
}

# Backup file with timestamp
backup() {
    cp "$1" "$1.$(date +%Y%m%d_%H%M%S).bak"
}